export default[
  {
    "login": "thazhemadam",
    "id": 47104651,
    "node_id": "MDQ6VXNlcjQ3MTA0NjUx",
    "avatar_url": "https://avatars.githubusercontent.com/u/47104651?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/thazhemadam",
    "html_url": "https://github.com/thazhemadam",
    "followers_url": "https://api.github.com/users/thazhemadam/followers",
    "following_url": "https://api.github.com/users/thazhemadam/following{/other_user}",
    "gists_url": "https://api.github.com/users/thazhemadam/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/thazhemadam/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/thazhemadam/subscriptions",
    "organizations_url": "https://api.github.com/users/thazhemadam/orgs",
    "repos_url": "https://api.github.com/users/thazhemadam/repos",
    "events_url": "https://api.github.com/users/thazhemadam/events{/privacy}",
    "received_events_url": "https://api.github.com/users/thazhemadam/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "shlokalakka",
    "id": 51351213,
    "node_id": "MDQ6VXNlcjUxMzUxMjEz",
    "avatar_url": "https://avatars.githubusercontent.com/u/51351213?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/shlokalakka",
    "html_url": "https://github.com/shlokalakka",
    "followers_url": "https://api.github.com/users/shlokalakka/followers",
    "following_url": "https://api.github.com/users/shlokalakka/following{/other_user}",
    "gists_url": "https://api.github.com/users/shlokalakka/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/shlokalakka/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/shlokalakka/subscriptions",
    "organizations_url": "https://api.github.com/users/shlokalakka/orgs",
    "repos_url": "https://api.github.com/users/shlokalakka/repos",
    "events_url": "https://api.github.com/users/shlokalakka/events{/privacy}",
    "received_events_url": "https://api.github.com/users/shlokalakka/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Ajitesh27",
    "id": 51512010,
    "node_id": "MDQ6VXNlcjUxNTEyMDEw",
    "avatar_url": "https://avatars.githubusercontent.com/u/51512010?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Ajitesh27",
    "html_url": "https://github.com/Ajitesh27",
    "followers_url": "https://api.github.com/users/Ajitesh27/followers",
    "following_url": "https://api.github.com/users/Ajitesh27/following{/other_user}",
    "gists_url": "https://api.github.com/users/Ajitesh27/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Ajitesh27/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Ajitesh27/subscriptions",
    "organizations_url": "https://api.github.com/users/Ajitesh27/orgs",
    "repos_url": "https://api.github.com/users/Ajitesh27/repos",
    "events_url": "https://api.github.com/users/Ajitesh27/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Ajitesh27/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "legalvenom",
    "id": 78557780,
    "node_id": "MDQ6VXNlcjc4NTU3Nzgw",
    "avatar_url": "https://avatars.githubusercontent.com/u/78557780?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/legalvenom",
    "html_url": "https://github.com/legalvenom",
    "followers_url": "https://api.github.com/users/legalvenom/followers",
    "following_url": "https://api.github.com/users/legalvenom/following{/other_user}",
    "gists_url": "https://api.github.com/users/legalvenom/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/legalvenom/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/legalvenom/subscriptions",
    "organizations_url": "https://api.github.com/users/legalvenom/orgs",
    "repos_url": "https://api.github.com/users/legalvenom/repos",
    "events_url": "https://api.github.com/users/legalvenom/events{/privacy}",
    "received_events_url": "https://api.github.com/users/legalvenom/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "mrinal-pandey",
    "id": 43128909,
    "node_id": "MDQ6VXNlcjQzMTI4OTA5",
    "avatar_url": "https://avatars.githubusercontent.com/u/43128909?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mrinal-pandey",
    "html_url": "https://github.com/mrinal-pandey",
    "followers_url": "https://api.github.com/users/mrinal-pandey/followers",
    "following_url": "https://api.github.com/users/mrinal-pandey/following{/other_user}",
    "gists_url": "https://api.github.com/users/mrinal-pandey/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mrinal-pandey/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mrinal-pandey/subscriptions",
    "organizations_url": "https://api.github.com/users/mrinal-pandey/orgs",
    "repos_url": "https://api.github.com/users/mrinal-pandey/repos",
    "events_url": "https://api.github.com/users/mrinal-pandey/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mrinal-pandey/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Venkatavaradan-R",
    "id": 44594675,
    "node_id": "MDQ6VXNlcjQ0NTk0Njc1",
    "avatar_url": "https://avatars.githubusercontent.com/u/44594675?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Venkatavaradan-R",
    "html_url": "https://github.com/Venkatavaradan-R",
    "followers_url": "https://api.github.com/users/Venkatavaradan-R/followers",
    "following_url": "https://api.github.com/users/Venkatavaradan-R/following{/other_user}",
    "gists_url": "https://api.github.com/users/Venkatavaradan-R/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Venkatavaradan-R/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Venkatavaradan-R/subscriptions",
    "organizations_url": "https://api.github.com/users/Venkatavaradan-R/orgs",
    "repos_url": "https://api.github.com/users/Venkatavaradan-R/repos",
    "events_url": "https://api.github.com/users/Venkatavaradan-R/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Venkatavaradan-R/received_events",
    "type": "User",
    "site_admin": false
  },
];